version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - backend

  - package-ecosystem: npm
    directory: /admin-frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - admin-frontend

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
