import type { Config } from "tailwindcss";

/** Vibrant cosmetics-forward palette (blush surfaces, fuchsia primary, violet secondary). */
const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#fcd34d",
        surface: "#fff7fb",
        "tertiary-container": "#78350f",
        "error-container": "#ffdad6",
        "surface-container-highest": "#ffc4e1",
        "surface-container-low": "#fff0f7",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#fbcfe8",
        "secondary-fixed": "#ede9fe",
        "on-secondary-container": "#3b0764",
        "inverse-primary": "#f472b6",
        "on-primary-fixed": "#3a0a2e",
        "on-background": "#3a0a2e",
        "primary-fixed": "#fce7f3",
        "surface-tint": "#9d174d",
        secondary: "#a855f7",
        "on-primary-container": "#fda5d5",
        "surface-dim": "#ffe8f4",
        "on-tertiary-container": "#92400e",
        "on-surface": "#3a0a2e",
        "surface-container": "#ffecf5",
        background: "#fff7fb",
        "tertiary-fixed": "#fef3c7",
        outline: "#c4a4b8",
        "inverse-on-surface": "#ffe4f3",
        "surface-container-high": "#ffd8ec",
        "on-secondary-fixed": "#3b0764",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#7c3aed",
        "on-tertiary": "#1c0a12",
        "surface-variant": "#ffd8ec",
        tertiary: "#f59e0b",
        "on-primary-fixed-variant": "#831843",
        "inverse-surface": "#1e0a1a",
        "on-tertiary-fixed-variant": "#92400e",
        "secondary-fixed-dim": "#ddd6fe",
        "surface-bright": "#fff7fb",
        "on-tertiary-fixed": "#451a03",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#6d28d9",
        primary: "#ec4899",
        error: "#dc2626",
        "primary-container": "#3b0a2d",
        "outline-variant": "#e8cfe0",
        "on-surface-variant": "#6b4d63",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
