import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95f",
        surface: "#f8f9ff",
        "tertiary-container": "#2a1700",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#fcd4dc",
        "secondary-fixed": "#f0e6ee",
        "on-secondary-container": "#3b2430",
        "inverse-primary": "#F48B9A",
        "on-primary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "primary-fixed": "#dae2fd",
        "surface-tint": "#565e74",
        secondary: "#452d3d",
        "on-primary-container": "#7c839b",
        "surface-dim": "#cbdbf5",
        "on-tertiary-container": "#b87500",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        background: "#f8f9ff",
        "tertiary-fixed": "#ffddb8",
        outline: "#76777d",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed": "#00174b",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#6b4256",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d3e4fe",
        tertiary: "#000000",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-surface": "#213145",
        "on-tertiary-fixed-variant": "#653e00",
        "secondary-fixed-dim": "#dcc8d4",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#1f1014",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5a3d4d",
        primary: "#F48B9A",
        error: "#ba1a1a",
        "primary-container": "#3a1f32",
        "outline-variant": "#c6c6cd",
        "on-surface-variant": "#45464d",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
