import type { Config } from "tailwindcss";

/** Jungle · opal · morning — mist greens, teal opal, dawn gold. */
const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#e8d4b8",
        surface: "#f2f7f5",
        "tertiary-container": "#3d3428",
        "error-container": "#ffdad6",
        "surface-container-highest": "#c8ddd6",
        "surface-container-low": "#e8f2ee",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b8ddd4",
        "secondary-fixed": "#d6e8ec",
        "on-secondary-container": "#d6eef2",
        "inverse-primary": "#4a9e8c",
        "on-primary-fixed": "#0f1f1c",
        "on-background": "#142824",
        "primary-fixed": "#d4eee8",
        "surface-tint": "#2d6a5f",
        secondary: "#3d6f78",
        "on-primary-container": "#b8e0d6",
        "surface-dim": "#e4efeb",
        "on-tertiary-container": "#5c4d38",
        "on-surface": "#142824",
        "surface-container": "#e0ebe7",
        background: "#eef6f3",
        "tertiary-fixed": "#f2e6d4",
        outline: "#8ca8a0",
        "inverse-on-surface": "#142824",
        "surface-container-high": "#d8e8e3",
        "on-secondary-fixed": "#0c2420",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#2a4f56",
        "on-tertiary": "#1a1510",
        "surface-variant": "#d0e4de",
        tertiary: "#b8956a",
        "on-primary-fixed-variant": "#2a4f48",
        "inverse-surface": "#f7faf9",
        "on-tertiary-fixed-variant": "#5c4d38",
        "secondary-fixed-dim": "#b8d0d8",
        "surface-bright": "#f7faf9",
        "on-tertiary-fixed": "#2a2218",
        "on-primary": "#f5fbfa",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#1a3a40",
        primary: "#1e5c52",
        error: "#b91c1c",
        "primary-container": "#0c2420",
        "outline-variant": "#c5d5cf",
        "on-surface-variant": "#4a635c",
        "on-error": "#ffffff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};

export default config;
